export const ACTION_TYPES = {
    INICIAR_CONSULTA_CLIMA: 'INICIAR_CONSULTA_CLIMA',
    CONSULTA_CLIMA_EXITO: 'CONSULTA_CLIMA_EXITO',
    CONSULTA_CLIMA_ERROR: 'CONSULTA_CLIMA_ERROR',
    ELIMINAR_ITEM_CLIMA: 'ELIMINAR_ITEM_CLIMA'
}
